### ISSUE TITLE
В Info.plist нет ключа для автоматического переключения GPU

### ISSUE THREAD

**Issue by photovirus** [PetrovVadim/GPU-Switch-Test#1]
[Эпол пишет,](https://developer.apple.com/library/mac/qa/qa1734/_index.html) что для автоматического переключения нужно добавить в `Info.plist` ключик `NSSupportsAutomaticGraphicsSwitching`, и тогда видюшки будут переключаться автоматически.

(На хабре я не зареган, так что пишу сюда. :)

**Comment by PetrovVadim** [comment]
Спасибо. Да, я в курсе про это.
Я даже пытался использовать не документированный флаг kCGLPFASupportsAutomaticGraphicsSwitching
К сожалению, это никак не помогло мне переключать GPU по требованию.

**Comment by photovirus** [comment]
И инструкцию по ссылке тоже пробовал? https://developer.apple.com/library/mac/technotes/tn2229/_index.html
Мало ли, может, ещё какие ошибки.

Мне кажется, хабрапост надо обновить с учётом всех эпловских документов, а то совершенно не очевидно, что всё по гайдлайнам.

**Comment by PetrovVadim** [comment]
Да, у меня даже есть на нее ссылка в посте. Все по гайдам.
Более того, https://code.google.com/p/chromium/codesearch#chromium/src/ui/gl/gl_context_cgl.cc&l=104 вот тут код хромиума.
А вот тут https://code.google.com/p/chromium/issues/detail?id=338925#c4 судя по всему и сделала Apple поблажку для google.
"After discussion with Apple it was learned that we didn't need to actually delete and re-create those contexts. We just needed to allocate all the contexts (including the WebGL contexts) with kCGLPFAAllowOfflineRenderers:YES, and when we wanted to switch to the discrete GPU, simply allocate a standalone CGLPixelFormatObj without that specified. When we wanted to switch back to the integrated GPU, delete that CGLPixelFormatObj."

**Comment by photovirus** [comment]
Ок, понял, спасибо. 😊
